spring.application.name=collaborative-canvas

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/collaborative_canvas?options=-c%20TimeZone%3DUTC}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
